## Preprocessing

In [ ]:
# Import our dependencies
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
import pandas as pd
import tensorflow as tf

#  Import and read the charity_data.csv.
import pandas as pd
application_df = pd.read_csv("https://static.bc-edx.com/data/dl-1-2/m21/lms/starter/charity_data.csv")
application_df.head()

,EIN,NAME,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,10520599,BLUE KNIGHTS MOTORCYCLE CLUB,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,10531628,AMERICAN CHESAPEAKE CLUB CHARITABLE TR,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,10547893,ST CLOUD PROFESSIONAL FIREFIGHTERS,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,10553066,SOUTHSIDE ATHLETIC ASSOCIATION,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,10556103,GENETIC RESEARCH INSTITUTE OF THE DESERT,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Drop the non-beneficial ID columns, 'EIN' and 'NAME'.
application_df = application_df.drop(columns=['EIN', 'NAME'])
application_df.head()

,APPLICATION_TYPE,AFFILIATION,CLASSIFICATION,USE_CASE,ORGANIZATION,STATUS,INCOME_AMT,SPECIAL_CONSIDERATIONS,ASK_AMT,IS_SUCCESSFUL
0,T10,Independent,C1000,ProductDev,Association,1,0,N,5000,1
1,T3,Independent,C2000,Preservation,Co-operative,1,1-9999,N,108590,1
2,T5,CompanySponsored,C3000,ProductDev,Association,1,0,N,5000,0
3,T3,CompanySponsored,C2000,Preservation,Trust,1,10000-24999,N,6692,1
4,T3,Independent,C1000,Heathcare,Trust,1,100000-499999,N,142590,1

In [ ]:
# Determine the number of unique values in each column.
application_df.nunique()

APPLICATION_TYPE            17
AFFILIATION                  6
CLASSIFICATION              71
USE_CASE                     5
ORGANIZATION                 4
STATUS                       2
INCOME_AMT                   9
SPECIAL_CONSIDERATIONS       2
ASK_AMT                   8747
IS_SUCCESSFUL                2
dtype: int64

In [ ]:
# Look at APPLICATION_TYPE value counts to identify and replace with "Other"
application_counts = application_df['APPLICATION_TYPE'].value_counts()
application_counts

APPLICATION_TYPE
T3     27037
T4      1542
T6      1216
T5      1173
T19     1065
T8       737
T7       725
T10      528
T9       156
T13       66
T12       27
T2        16
T25        3
T14        3
T29        2
T15        2
T17        1
Name: count, dtype: int64

In [ ]:
# Choose a cutoff value and create a list of application types to be replaced
# use the variable name `application_types_to_replace`
application_types_to_replace = application_counts[application_counts < 200].index.tolist()
# Replace in dataframe
for app in application_types_to_replace:
    application_df['APPLICATION_TYPE'] = application_df['APPLICATION_TYPE'].replace(app,"Other")

# Check to make sure replacement was successful
application_df['APPLICATION_TYPE'].value_counts()

APPLICATION_TYPE
T3       27037
T4        1542
T6        1216
T5        1173
T19       1065
T8         737
T7         725
T10        528
Other      276
Name: count, dtype: int64

In [ ]:
# Look at CLASSIFICATION value counts to identify and replace with "Other"
classification_counts = application_df['CLASSIFICATION'].value_counts()
classification_counts.head()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Name: count, dtype: int64

In [ ]:
# You may find it helpful to look at CLASSIFICATION value counts >1
classifications_greater_than_1 = classification_counts[classification_counts > 1]
classifications_greater_than_1

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
C7000      777
C1700      287
C4000      194
C5000      116
C1270      114
C2700      104
C2800       95
C7100       75
C1300       58
C1280       50
C1230       36
C1400       34
C7200       32
C2300       32
C1240       30
C8000       20
C7120       18
C1500       16
C1800       15
C6000       15
C1250       14
C8200       11
C1238       10
C1278       10
C1235        9
C1237        9
C7210        7
C2400        6
C1720        6
C4100        6
C1257        5
C1600        5
C1260        3
C2710        3
C0           3
C3200        2
C1234        2
C1246        2
C1267        2
C1256        2
Name: count, dtype: int64

In [ ]:
classifications_greater_than_1.nunique()

32

In [ ]:
# Choose a cutoff value and create a list of classifications to be replaced
# use the variable name `classifications_to_replace`
classifications_to_replace = classification_counts[classification_counts < 500].index.tolist()

# Replace in dataframe
for cls in classifications_to_replace:
    application_df['CLASSIFICATION'] = application_df['CLASSIFICATION'].replace(cls,"Other")

# Check to make sure replacement was successful
application_df['CLASSIFICATION'].value_counts()

CLASSIFICATION
C1000    17326
C2000     6074
C1200     4837
C3000     1918
C2100     1883
Other     1484
C7000      777
Name: count, dtype: int64

In [ ]:
# Convert categorical data to numeric with `pd.get_dummies`
dummy_application_df = pd.get_dummies(application_df)
dummy_application_df.head()

,STATUS,ASK_AMT,IS_SUCCESSFUL,APPLICATION_TYPE_Other,APPLICATION_TYPE_T10,APPLICATION_TYPE_T19,APPLICATION_TYPE_T3,APPLICATION_TYPE_T4,APPLICATION_TYPE_T5,APPLICATION_TYPE_T6,...,INCOME_AMT_1-9999,INCOME_AMT_10000-24999,INCOME_AMT_100000-499999,INCOME_AMT_10M-50M,INCOME_AMT_1M-5M,INCOME_AMT_25000-99999,INCOME_AMT_50M+,INCOME_AMT_5M-10M,SPECIAL_CONSIDERATIONS_N,SPECIAL_CONSIDERATIONS_Y
0,1,5000,1,False,True,False,False,False,False,False,...,False,False,False,False,False,False,False,False,True,False
1,1,108590,1,False,False,False,True,False,False,False,...,True,False,False,False,False,False,False,False,True,False
2,1,5000,0,False,False,False,False,False,True,False,...,False,False,False,False,False,False,False,False,True,False
3,1,6692,1,False,False,False,True,False,False,False,...,False,True,False,False,False,False,False,False,True,False
4,1,142590,1,False,False,False,True,False,False,False,...,False,False,True,False,False,False,False,False,True,False

In [ ]:
# Split our preprocessed data into our features and target arrays
X = dummy_application_df.drop(columns=['IS_SUCCESSFUL'])
y = dummy_application_df['IS_SUCCESSFUL']

# Split the preprocessed data into a training and testing dataset
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.25, random_state=42)

In [ ]:
# Create a StandardScaler instances
scaler = StandardScaler()

# Fit the StandardScaler
X_scaler = scaler.fit(X_train)

# Scale the data
X_train_scaled = X_scaler.transform(X_train)
X_test_scaled = X_scaler.transform(X_test)

## Compile, Train and Evaluate the Model

In [ ]:
# Define the model - deep neural net, i.e., the number of input features and hidden nodes for each layer.
nn = tf.keras.models.Sequential()

# First hidden layer
nn.add(tf.keras.layers.Dense(units=80, activation='relu', input_dim=X_train_scaled.shape[1]))

# Second hidden layer
nn.add(tf.keras.layers.Dense(units=30, activation='relu'))

# Output layer
nn.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

# Check the structure of the model
nn.summary()

/usr/local/lib/python3.10/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━┓
┃ Layer (type)                         ┃ Output Shape                ┃         Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━┩
│ dense (Dense)                        │ (None, 80)                  │           3,600 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_1 (Dense)                      │ (None, 30)                  │           2,430 │
├──────────────────────────────────────┼─────────────────────────────┼─────────────────┤
│ dense_2 (Dense)                      │ (None, 1)                   │              31 │
└──────────────────────────────────────┴─────────────────────────────┴─────────────────┘

 Total params: 6,061 (23.68 KB)

 Trainable params: 6,061 (23.68 KB)

 Non-trainable params: 0 (0.00 B)

In [ ]:
# Compile the model
nn.compile(loss='binary_crossentropy', optimizer='rmsprop', metrics=['accuracy'])

In [ ]:
# Train the model
nn.fit(X_train_scaled, y_train, epochs=100, batch_size = 1)

Epoch 1/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 54s 2ms/step - accuracy: 0.7196 - loss: 0.6304
Epoch 2/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 74s 2ms/step - accuracy: 0.7238 - loss: 0.6358
Epoch 3/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 82s 2ms/step - accuracy: 0.7254 - loss: 0.6581
Epoch 4/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 79s 2ms/step - accuracy: 0.7230 - loss: 0.6494
Epoch 5/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.7197 - loss: 0.6671
Epoch 6/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 79s 2ms/step - accuracy: 0.7250 - loss: 0.7048
Epoch 7/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.7240 - loss: 0.6915
Epoch 8/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 82s 2ms/step - accuracy: 0.7287 - loss: 0.6884
Epoch 9/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7185 - loss: 0.6921
Epoch 10/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.7205 - loss: 0.6892
Epoch 11/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 79s 2ms/step - accuracy: 0.7226 - loss: 0.6792
Epoch 12/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.7190 - loss: 0.6783
Epoch 13/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.7121 - loss: 0.6915
Epoch 14/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7224 - loss: 0.6875
Epoch 15/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 81s 2ms/step - accuracy: 0.7207 - loss: 0.7266
Epoch 16/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.7274 - loss: 0.7384
Epoch 17/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.7227 - loss: 0.7386
Epoch 18/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.7215 - loss: 0.7470
Epoch 19/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.7160 - loss: 0.7829
Epoch 20/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7227 - loss: 0.8145
Epoch 21/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7185 - loss: 0.8024
Epoch 22/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 83s 2ms/step - accuracy: 0.7277 - loss: 0.7644
Epoch 23/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.7229 - loss: 0.7853
Epoch 24/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.7220 - loss: 0.7803
Epoch 25/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 39s 2ms/step - accuracy: 0.7227 - loss: 0.7979
Epoch 26/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 47s 2ms/step - accuracy: 0.7185 - loss: 0.8213
Epoch 27/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 78s 2ms/step - accuracy: 0.7202 - loss: 0.7977
Epoch 28/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.7203 - loss: 0.8338
Epoch 29/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.7204 - loss: 0.9696
Epoch 30/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.7194 - loss: 1.2088
Epoch 31/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.7178 - loss: 0.9867
Epoch 32/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.7147 - loss: 1.1383
Epoch 33/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7174 - loss: 0.9210
Epoch 34/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.7127 - loss: 0.9196
Epoch 35/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 82s 2ms/step - accuracy: 0.7195 - loss: 0.8431
Epoch 36/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7184 - loss: 0.8102
Epoch 37/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.7150 - loss: 0.8164
Epoch 38/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 80s 2ms/step - accuracy: 0.7147 - loss: 0.8556
Epoch 39/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 81s 2ms/step - accuracy: 0.7204 - loss: 0.8585
Epoch 40/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7116 - loss: 0.8293
Epoch 41/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.7107 - loss: 0.8950
Epoch 42/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 79s 2ms/step - accuracy: 0.7186 - loss: 0.9225
Epoch 43/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7240 - loss: 0.9550
Epoch 44/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.7120 - loss: 1.0085
Epoch 45/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.7060 - loss: 1.0445
Epoch 46/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 83s 2ms/step - accuracy: 0.7125 - loss: 0.9538
Epoch 47/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7129 - loss: 0.9129
Epoch 48/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.7035 - loss: 0.8752
Epoch 49/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7036 - loss: 0.9050
Epoch 50/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7077 - loss: 0.9122
Epoch 51/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.7044 - loss: 0.9235
Epoch 52/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 83s 2ms/step - accuracy: 0.7079 - loss: 0.9292
Epoch 53/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.7062 - loss: 0.8766
Epoch 54/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 92s 2ms/step - accuracy: 0.7101 - loss: 0.9021
Epoch 55/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 69s 2ms/step - accuracy: 0.7022 - loss: 0.9987
Epoch 56/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.6976 - loss: 1.0511
Epoch 57/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.6998 - loss: 0.9761
Epoch 58/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.6952 - loss: 0.9664
Epoch 59/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 81s 2ms/step - accuracy: 0.6952 - loss: 0.9032
Epoch 60/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.6956 - loss: 1.0042
Epoch 61/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.6973 - loss: 0.9908
Epoch 62/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.6974 - loss: 0.9897
Epoch 63/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 39s 2ms/step - accuracy: 0.6933 - loss: 1.0674
Epoch 64/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.6996 - loss: 1.2057
Epoch 65/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 78s 1ms/step - accuracy: 0.6915 - loss: 1.2022
Epoch 66/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.6893 - loss: 1.1942
Epoch 67/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.6869 - loss: 1.2071
Epoch 68/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.6929 - loss: 1.1399
Epoch 69/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 81s 2ms/step - accuracy: 0.6874 - loss: 1.1660
Epoch 70/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 84s 2ms/step - accuracy: 0.6873 - loss: 1.1360
Epoch 71/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 82s 2ms/step - accuracy: 0.6774 - loss: 1.1670
Epoch 72/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 79s 2ms/step - accuracy: 0.6904 - loss: 1.2222
Epoch 73/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.6811 - loss: 1.1898
Epoch 74/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.6896 - loss: 1.1600
Epoch 75/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.6900 - loss: 1.1464
Epoch 76/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.6793 - loss: 1.1317
Epoch 77/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 44s 2ms/step - accuracy: 0.6842 - loss: 1.1467
Epoch 78/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.6727 - loss: 1.1114
Epoch 79/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.6690 - loss: 1.1367
Epoch 80/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.6849 - loss: 1.1910
Epoch 81/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 81s 2ms/step - accuracy: 0.6865 - loss: 1.1540
Epoch 82/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 83s 2ms/step - accuracy: 0.6824 - loss: 1.1512
Epoch 83/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 80s 2ms/step - accuracy: 0.6920 - loss: 1.1163
Epoch 84/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.6924 - loss: 1.1367
Epoch 85/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 40s 2ms/step - accuracy: 0.6968 - loss: 1.1037
Epoch 86/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 42s 2ms/step - accuracy: 0.6874 - loss: 1.1480
Epoch 87/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 83s 2ms/step - accuracy: 0.6923 - loss: 1.1678
Epoch 88/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 45s 2ms/step - accuracy: 0.6878 - loss: 1.1706
Epoch 89/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 41s 2ms/step - accuracy: 0.6811 - loss: 1.1361
Epoch 90/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 86s 2ms/step - accuracy: 0.6872 - loss: 1.1355
Epoch 91/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.6893 - loss: 1.1166
Epoch 92/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 45s 2ms/step - accuracy: 0.6855 - loss: 1.1404
Epoch 93/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 81s 2ms/step - accuracy: 0.6835 - loss: 1.1893
Epoch 94/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.6766 - loss: 1.1961
Epoch 95/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 83s 2ms/step - accuracy: 0.6852 - loss: 1.1871
Epoch 96/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.6781 - loss: 1.2141
Epoch 97/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 43s 2ms/step - accuracy: 0.6819 - loss: 1.2733
Epoch 98/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 83s 2ms/step - accuracy: 0.6764 - loss: 1.2801
Epoch 99/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 45s 2ms/step - accuracy: 0.6749 - loss: 1.2581
Epoch 100/100
25724/25724 ━━━━━━━━━━━━━━━━━━━━ 45s 2ms/step - accuracy: 0.6814 - loss: 1.3377

In [ ]:
# Evaluate the model using the test data
model_loss, model_accuracy = nn.evaluate(X_test_scaled,y_test,verbose=2)
print(f"Loss: {model_loss}, Accuracy: {model_accuracy}")

268/268 - 1s - 4ms/step - accuracy: 0.5895 - loss: 1.3562
Loss: 1.356166958808899, Accuracy: 0.5895043611526489

In [ ]:
# Export our model to HDF5 file
nn.save('AlphabetSoupCharity.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.